name: GitHub Script Test
on:
  issues:
    types: closed
jobs:
  job1:
    runs-on: self-hosted
    steps:
      - uses: actions/github-script@v3
        with:
          script: |
            console.log(
              github.issues.listComments({
                owner: context.payload.repository.owner.login,
                repo: context.payload.repository.name,
                issue_number: context.payload.issue.number
              })
            )
