name: GitHub Script Test
on:
  issues:
    types: closed
jobs:
  job1:
    runs-on: self-hosted
    steps:
      - uses: actions/github-script@v3
        with:
          script: |
            const comments = await github.issues.listComments({
              owner: 'qmacro',
              repo: 'actions-test',
              issue_number: 1
            })
            if (comments.length > 0) console.log(comments[comments.length - 1].body)
